Updated engr 101 matlab image to install packages with MPM

diff --git a/engr101/Dockerfile b/engr101/Dockerfile
--- a/engr101/Dockerfile
+++ b/engr101/Dockerfile
@@ -1,17 +1,72 @@
-FROM mathworks/matlab:r2021b
-COPY license.dat /license.dat
+# See https://github.com/mathworks-ref-arch/matlab-dockerfile
 
-ENV MLM_LICENSE_FILE=/license.dat
+# Copyright 2019 - 2022 The MathWorks, Inc.
+
+# To specify which MATLAB release to install in the container, edit the value of the MATLAB_RELEASE argument.
+# Use lower case to specify the release, for example: ARG MATLAB_RELEASE=r2021b
+ARG MATLAB_RELEASE=r2021b
+
+# When you start the build stage, this Dockerfile by default uses the Ubuntu-based matlab-deps image.
+# To check the available matlab-deps images, see: https://hub.docker.com/r/mathworks/matlab-deps
+FROM mathworks/matlab-deps:${MATLAB_RELEASE}
+
+# Declare the global argument to use at the current build stage
+ARG MATLAB_RELEASE
+
+# Install mpm dependencies & tini
+RUN export DEBIAN_FRONTEND=noninteractive \
+    && apt-get update \
+    && apt-get install --no-install-recommends --yes \
+    wget \
+    unzip \
+    ca-certificates \
+    tini \
+    && apt-get clean \
+    && apt-get autoremove \
+    && rm -rf /var/lib/apt/lists/*
+
+# Run mpm to install MATLAB in the target location and delete the mpm installation afterwards.
+# If mpm fails to install successfully then output the logfile to the terminal, otherwise cleanup.
+RUN wget -q https://www.mathworks.com/mpm/glnxa64/mpm \ 
+    && chmod +x mpm \
+    && ./mpm install \
+    --release=${MATLAB_RELEASE} \
+    --destination=/opt/matlab \
+    --products MATLAB Image_Processing_Toolbox Statistics_and_Machine_Learning_Toolbox \
+    || (echo "MPM Installation Failure. See below for more information:" && cat /tmp/mathworks_root.log && false) \
+    && rm -f mpm /tmp/mathworks_root.log \
+    && ln -s /opt/matlab/bin/matlab /usr/local/bin/matlab
+
+# Add "matlab" user and grant sudo permission.
+RUN adduser --shell /bin/bash --disabled-password --gecos "" matlab \
+    && echo "matlab ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/matlab \
+    && chmod 0440 /etc/sudoers.d/matlab
+
+# One of the following 2 ways of configuring the license server to use must be
+# uncommented.
+
+# ARG LICENSE_SERVER
+# # Specify the host and port of the machine that serves the network licenses 
+# # if you want to bind in the license info as an environment variable. This 
+# # is the preferred option for licensing. It is either possible to build with 
+# # something like --build-arg LICENSE_SERVER=27000@MyServerName, alternatively
+# # you could specify the license server directly using
+# #       ENV MLM_LICENSE_FILE=27000@flexlm-server-name
+# ENV MLM_LICENSE_FILE=$LICENSE_SERVER
+
+# Alternatively you can put a license file into the container.
+# You should fill this file out with the details of the license 
+# server you want to use and uncomment the following line.
+COPY license.dat /opt/matlab/licenses/
+
+# ENV MLM_LICENSE_FILE=/license.dat
+
+# Autograder image requirements follow
 
 CMD ["/bin/bash"]
 ENTRYPOINT []
 
 USER root
-
-# See https://github.com/mathworks-ref-arch/matlab-dockerfile/blob/main/MPM.md
-RUN wget -P /usr/bin https://www.mathworks.com/mpm/glnxa64/mpm
-RUN chmod 744 /usr/bin/mpm
-RUN mpm install --release=r2021b --destination=/home/autograder/matlab --products MATLAB Image_Processing_Toolbox Statistics_and_Machine_Learning_Toolbox
 
 RUN apt-get update --fix-missing && apt-get install -y python3
 
